name: Auto-merge PRs

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@6b90055d91c96696dc9ff8de77723a2cf30e5570"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AUTOMERGE: "automerge"
