name: Publish playlists

on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: npm install

    - name: Generate Playlists
      run: npm run generate

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: .gh-pages
  update-readme:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Install Dependencies
      run: npm install
      
    - name: Update README.md
      run: npm run update-readme
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
        COMMIT_MESSAGE: 'Update README.md'
        PULL_REQUEST_BRANCH: bot-patch
        PULL_REQUEST_TITLE: '[Bot] Update README.md'
        PULL_REQUEST_LABELS: automerge
        PULL_REQUEST_BODY: >
        
        - name: Lightstep Pre-Deploy Check
  # You may pin to the exact commit or the version.
  # uses: lightstep/lightstep-action-predeploy@6b90055d91c96696dc9ff8de77723a2cf30e5570
  uses: lightstep/lightstep-action-predeploy@v0.2.6
  with:
    # The organization associated with your Lightstep account (usually your company name)
    lightstep_organization: # optional
    # The Lightstep project associated with this repository
    lightstep_project: # optional
    # The key to access the Lightstep Public API
    lightstep_api_key: # optional
    # The token to access the Rollbar API
    rollbar_api_token: # optional
    # The token to access the PagerDuty API
    pagerduty_api_token: # optional
    # If set to true, collapse all conditions to a single table row
    rollup_conditions: # optional
    # If set to true, will not add a comment to pull-requests
    disable_comment: # optional
            This pull request is auto-generated by GitHub action.
