AWSTemplateFormatVersion: '2010-09-09'
2
Transform: AWS::Serverless-2016-10-31
3
Description: >
4
  GitHub Actions demonstration App
5
Resources:
6
  ApiGatewayApi:
7
    Type: AWS::Serverless::Api
8
    Properties:
9
      StageName: Prod
10
    Auth:
11
     UsagePlan:
12
      CreateUsagePlan: PER_API
13
      Description: Usage plan for this API
14
      Quota:
15
       Limit: 500
16
       Period: MONTH
17
      Throttle:
18
       BurstLimit: 100
19
       RateLimit: 50
20
  LamdbaFunction:
21
    Type: AWS::Serverless::Function
22
    Properties:
23
      CodeUri: ./    
24
      Handler: lambda.handler
25
      Runtime: python3.8
26
      Events:
27
        getCounter:
28
          Type: Api
29
          Properties:
30
            Path: /hello
31
            Method: get
32
            RestApiId: !Ref ApiGatewayApi
